---
kind: ConfigMap
apiVersion: v1
metadata:
  name: telegraf
  namespace: bench
data:
    telegraf.conf: |
        [agent]
            debug = true
            interval = "5s"

        [global_tags]
            node = "$NODE_NAME"

        [[inputs.kubernetes]]
            url = "https://$HOST_IP:10250"
            tls_ca = "/etc/kubernetes/pki/ca.crt"
            tls_cert = "/var/lib/kubelet/pki/kubelet-client-current.pem"
            tls_key = "/var/lib/kubelet/pki/kubelet-client-current.pem"
            insecure_skip_verify = true
            label_include = ['app', 'k8s-app']

        [[outputs.influxdb_v2]]
            urls = ["http://influxdb.influxdb.svc.cluster.local:8086"]
            token = "$INFLUX_AUTH_TOKEN"
            organization = "influx"
            bucket = "influx"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: bench
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
      annotations:
        config: "20201202"
    spec:
      priorityClassName: system-node-critical
      volumes:
      - name: kubelet-pki
        hostPath:
          path: /var/lib/kubelet/pki
          type: Directory
      - name: pki
        hostPath:
          path: /etc/kubernetes/pki
          type: Directory
      - name: conf
        configMap:
          name: telegraf
      containers:
      - image: telegraf:1.19
        name: telegraf
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        command:
        - /usr/bin/telegraf
        volumeMounts:
        - name: pki
          mountPath: /etc/kubernetes/pki
        - name: kubelet-pki
          mountPath: /var/lib/kubelet/pki
        - name: conf
          mountPath: /etc/telegraf
          readOnly: true
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.hostIP"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: "spec.nodeName"
        - name: INFLUX_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: sigbench
              key: influx-auth-token
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
